---
- name: Enable hosts to scalelite
  shell: >-
    docker exec $(docker ps -a | grep "Up" | awk '{print $NF}' | grep -w "{{ deploy_name }}_scalelite-api\.*") 
    ./bin/rake servers 
    | grep -o "id:.*$" | grep -o "[^ ]*$"
  register: instances
  failed_when:
    - instances.rc == 100

- name: Remove
  shell: >-
    docker exec $(docker ps -a | grep "Up" | awk '{print $NF}' | grep -w "{{ deploy_name }}_scalelite-api\.*")
    ./bin/rake servers:remove[{{ item }}]
  loop: 
    "{{ instances.stdout_lines|list }}"