---
- name: Enable hosts to scalelite
  shell: >-
    docker exec scalelite-api 
    ./bin/rake servers 
    | grep -o "id:.*$" | grep -o "[^ ]*$"
  register: instances
  failed_when:
    - instances.rc == 100

- name: Remove
  shell: >-
    docker exec scalelite-api 
    ./bin/rake servers:remove[{{ item }}]
  loop: 
    "{{ instances.stdout_lines|list }}"