---
- name: adapt letsencrypt standalone ports in ufw
  copy:
    content: |
      [letsencrypt]
      title=letsencrypt standalone on 80,443
      description=Standalone certbot certificate aquiring
      ports=80,443/tcp
    mode: 0644
    dest: /etc/ufw/applications.d/letsencrypt

- name: allow letsencrypt in ufw
  ufw:
    rule: allow
    name: letsencrypt
    state: enabled

- name: adapt coturn ports in ufw
  copy:
    content: |
      [turnserver]
      title=Coturn
      description=Free open source implementation of TURN and STUN Server
      ports={{ stun_port }},{{ turn_port }}/tcp|{{ stun_port }},{{ turn_port }},49152:65535/udp
    mode: 0644
    dest: /etc/ufw/applications.d/turnserver

- name: allow turnserver in ufw
  ufw:
    rule: allow
    name: turnserver
    state: enabled
