#!/usr/bin/env ansible-playbook
---
- name: Base
  hosts: all
  remote_user: root
  gather_facts: yes
  roles:
     - {
       role: toni.base,
       configure_firewall: 'true'
       }
     - {
        role: geerlingguy.ntp,
        ntp_manage_config: true,
        ntp_servers: [
          0.de.pool.ntp.org,
          1.de.pool.ntp.org,
          2.de.pool.ntp.org,
          3.de.pool.ntp.org
        ]
       }
  vars:
     configure_monitoring: "True"          
  # tasks:
  # - name: Deploy certificates
  #   when: existing_certs|bool
  #   import_role: { name: toni.certificates }
  #   tags: certs


- import_playbook: wireguard.yml
  when: configure_wireguard|bool
  tags: wireguard

- import_playbook: turnserver.yml
  tags: turn
  when: configure_turnserver|bool

- name: Setup BBB Server
  hosts: bigbluebutton
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.bigbluebutton,
        bbb_webhooks_enable: "true"
      } 

- name: Setup Loadbalancer scalelite
  hosts: scalelite
  remote_user: root
  gather_facts: yes
  roles:
    - toni.scalelite
  vars:
    - force_images: "True"
    - letsencrypt_email: "jidumailer@gmail.com"    
    - auth_provider_domain: "key.{{ domain }}"
    - nginx_domain: "{{ domain }}"
    - scalelite_db_init: "True"

- name: Configure BBB
  gather_facts: yes
  hosts: bigbluebutton
  handlers:
    - include: "/root/.ansible/roles/toni.openresty/handlers/main.yml"
  tasks:
  # - name: Firewall BBB
  #   when: configure_firewall|bool
  #   include_role: { name: toni.bigbluebutton, tasks_from: firewall }
  - name: Configure BBB SSL
    include_role: { name: toni.bigbluebutton, tasks_from: ssl }
  - name: Configure BBB Exporter
    when: configure_monitoring|bool
    include_role: { name: toni.bigbluebutton, tasks_from: monitoring }
  - name: Configure BBB Privacy 
    include_role: { name: toni.bigbluebutton, tasks_from: privacy }