#!/usr/bin/env ansible-playbook
- hosts: builder
  become: True
  gather_facts: yes
  roles:
    - {
        role: toni.base,
        configure_firewall: 'true'
      }
    - {
        role: toni.docker
      }
    - {
        role: geerlingguy.ntp,
        ntp_manage_config: true,
        ntp_servers: [
          0.de.pool.ntp.org,
          1.de.pool.ntp.org,
          2.de.pool.ntp.org,
          3.de.pool.ntp.org
        ]
      }
    - {
        role : toni.buildimages,
        nginx_domain: "{{ domain }}",
        force_rebuild: true, # is not workin -> always true // todo: repair tar check
      }
  vars:
    images:
      - { namespace: "registry.{{ registry }}", name: "openresty_base", tag: "1.21.4.1", basenamespace: "", basename: "alpine", basetag: "3.15" }
      - { namespace: "registry.{{ registry }}", name: "openresty_base_fat", tag: "1.21.4.1-alpine-fat", basenamespace: "", basename: "openresty_base", basetag: "1.21.4.1" }
      - { namespace: "registry.{{ registry }}", name: "openresty", tag: "1.21.4.1-alpine-fat", basenamespace: "", basename: "openresty_base_fat", basetag: "1.21.4.1-alpine-fat" }
      - { namespace: "registry.{{ registry }}", name: "scalelite", tag: "1.21.4.1-alpine-fat", basenamespace: "", basename: "openresty", basetag: "1.21.4.1-alpine-fat" }