#!/usr/bin/env ansible-playbook
- hosts: builder
  become: True
  gather_facts: yes
  roles:
    - {
        role: base,
        configure_firewall: 'true'
      }
    - {
        role: docker
      }
    - {
        role: geerlingguy.ntp,
        ntp_manage_config: true,
        ntp_servers: [
          0.de.pool.ntp.org,
          1.de.pool.ntp.org,
          2.de.pool.ntp.org,
          3.de.pool.ntp.org
        ]
      }
    - {
        role : toni.buildimages
      }
  vars:
    images:
      - { namespace: "registry.toni-media.com", name: "openresty_base", tag: "1.19.3.1-2", basenamespace: "", basename: "alpine", basetag: "3.12" }
      - { namespace: "registry.toni-media.com", name: "openresty_base_fat", tag: "1.19.3.1-2-alpine-fat", basenamespace: "", basename: "openresty_base", basetag: "1.19.3.1-2" }
      - { namespace: "registry.toni-media.com", name: "openresty", tag: "1.19.3.1-2-alpine-fat", basenamespace: "", basename: "openresty_base_fat", basetag: "1.19.3.1-2-alpine-fat" }
      - { namespace: "registry.toni-media.com", name: "scalelite", tag: "1.19.3.1-2-alpine-fat", basenamespace: "", basename: "openresty", basetag: "1.19.3.1-2-alpine-fat" }