---
# - hosts: frontend
#   name: Include certificate facts
#   tasks:
#   - name: Certificate paths as facts
#     import_role: { name: toni.certificates, tasks_from: facts }

- hosts: frontend
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.docker,
        docker_network_driver: 'overlay', #trigger swarm
        node_exporter_ip: "{{ wg_client_ip|default('10.8.0.1') }}",
        #swarm_interface: "{{ ansible_default_ipv4['interface'] }}", #default wg0
        tags: [ host, docker ]
      }

- hosts: frontend
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.openresty,
        openresty_image: "registry.toni-media.com_openresty:1.21.4.1-alpine-fat",
        force_images: true,
        nginx_run_as: 'stack',
        nginx_swarm_real_ip: true,
        nginx_domain: "{{ domain }}",
        nginx_stack: "openresty",
        tags: [ host, openresty ]
      }
    - {
        role: toni.keycloak, 
        auth_bypass: "true",
        nginx_run_as: 'stack',
        deploy_name: "key",
        nginx_domain: "{{ domain }}",
        keycloak_server: "{{ auth_provider_domain }}",
        keycloak_image: "quay.io/keycloak/keycloak:18.0.2",
        tags: [ keycloak ]
      }  

- hosts: frontend
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.greenlight,
        deploy_name: "greenlight",
        create_stack_network: true,
        stack_subnet: "10.10.17.0/24",
        force_images: true,
        create_kc_client: true,
        create_kc_role: true,
        create_kc_user: true,
        nginx_run_as: 'stack',
        nginx_domain: "{{ domain }}",
        nginx_subdomain: "ui.",
        keycloak_server: "{{ auth_provider_domain }}",
        greenlight_create_admin: false,
        include_auth: true,
        tags: [ greenlight ]
      }

- hosts: wg_server
  name: wg ip facts (server) used by prometheus
  tasks:
  - name: facts
    import_role: { name: toni.wg-server, tasks_from: facts }

- hosts: wg_clients
  name: wg ip facts (clients) used by prometheus
  tasks:
  - name: facts
    import_role: { name: toni.wg-client, tasks_from: facts }


# seperated into second run
# greenlight / garfana default vars got messed/mixed?!
- hosts: frontend
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.grafana, 
        deploy_name: "grafana",
        create_stack_network: true,
        stack_subnet: "10.10.18.0/24",
        force_images: true,
        create_kc_client: true,
        create_kc_role: true,
        create_kc_user: true,        
        auth_bypass: "false",
        nginx_run_as: 'stack',
        nginx_domain: "{{ domain }}",
        nginx_subdomain: "mon.",
        keycloak_server: "{{ auth_provider_domain }}",
        tags: [ grafana ],
        when: configure_monitoring|bool
      }  
    - {
        role: toni.prometheus, 
        deploy_name: "prometheus",
        nginx_run_as: 'stack',
        nginx_domain: "{{ domain }}",
        tags: [ prometheus ],
        when: configure_monitoring|bool
      }    