---
user: "root"
user_path: "/root"
configure_ipv4_stack_hostname: true
configure_ipv6_stack_hostname: false
stack_network_name: 'grafana'

#grafana_image: "grafana/grafana:7.2.0"
grafana_image: "grafana/grafana:8.5.5"
grafana_pg_image: "postgres:13-alpine"
grafana_redis_image: "redis:6"
grafana_db_name: "grafana"
grafana_db_user: "grafana"
grafana_db_password: "UseVaultValueInstead"
grafana_admin_password: "UseVaultValueInstead"

nginx_domain: "{{ domain }}"
nginx_subdomain: "mon."

##Keycloak
access_group: "grafana"
keycloak_deploy_name: "key"
keycloak_realm: "Intern" # the realm which nginx is using in keycloak
keycloak_client_name: "Nginx" # client name in keycloak
keycloak_client_secret: "d3367b2d-85fb-46c0-9fcb-15e2dfeb4d9b" # dummy -> allways change!!
keycloak_temporary_pass: "a3D4f2n1_a1"
create_kc_role: false
create_kc_client: false
create_kc_user: false
keycloak_roles:
  - "grafana"
  - "grafana_editor"
  - "grafana_admin"
## only lowercase usernames!!!!
keycloak_users:
  - { username: "ace", email: "ace@{{domain}}", firstname: "A", lastname: "ce" }

dir_exists:
  - "{{ user_path }}/{{ deploy_name }}/backup"

# Add subpath to root_url if necessary
grafana_root_url: "https://{{ nginx_subdomain }}{{ nginx_domain }}"
grafana_data_dir: "/root/grafana/data"
grafana_prov_dir: "/root/grafana/prov"
#grafana_dashboard_dir: "/root/grafana/dashboard"
grafana_aliases: []
container_cert_path: "/etc/ssl/dummy-ssl-fallback.crt"
container_key_path: "/etc/ssl/dummy-ssl-fallback.key"