---
- name: Create prometheus directory
  file:
    state: directory
    path: "{{ user_path }}/prometheus"

- name: Create data directory
  file:
    state: directory
    path: "{{ prometheus_data_dir }}"

- name: Open tcp port
  ufw:
    rule: allow
    src: '10.10.11.0/24'
    port: "9100"
    proto: tcp

- name: Deploy docker-compose file
  template:
    src: docker-compose_prometheus.yml.j2
    dest: "{{ user_path }}/prometheus/docker-compose.yml"
  notify: restart prometheus

- name: Deploy prometheus config file
  template:
    src: prometheus.yml.j2
    dest: "{{ user_path }}/prometheus/prometheus.yml"
  notify: restart prometheus

- name: Launch docker-compose
  docker_compose:
    build: yes
    pull: yes
    project_src: "{{ user_path }}/prometheus"
